### ISSUE TITLE
search_covered issue

### ISSUE THREAD

**Issue by Edsall** [mjschultz/py-radix#26]
I am running with 0.9.4

When I do the following, I expect the result to be empty.  Instead, I get node '10.30.2.1/32'.

r = radix.Radix()
r.add('10.30.2.1/32')
r.add('10.30.2.1/25')
result = r.search_covered('10.30.2.64/32')

If the last byte of the search address is less than 0x40, it seems to work.

**Comment by sorc1** [comment]
I've created pull request 27 that fixes the issue. Please test it.

**Comment by Edsall** [comment]
That seems to have fixed it. 

Thanks.

**Comment by mjschultz** [comment]
Thanks @sorc1 for the fix and @Edsall for the bug report!

The fix should now be available via [`pip install py-radix==0.9.5`](https://pypi.python.org/pypi/py-radix/0.9.5)
